### ISSUE TITLE
Should we continue to use coalescent time internally?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsdate#137]
I find it a little confusing to be using coalescent times internally, rather than using generation times (or even real calendar dates). I wonder if it would be clearer for our own interpretation purposes to multiply the prior by 2Ne, and not use Ne in the edge likelihood calculations. That means we don't need to back-convert to generations when outputting the times, and it becomes clearer in my mind that the role of variable Ne only affects the prior (which is useful if e.g. we want to use anything other than the conditional coalescent prior)

On the other hand, I wonder if we chose coalescent time for the calculation because, being essentially "normalised" it is less susceptible to floating point error, or something? I guess it would be easy to test whether we see fp errors with some test cases if we swap Ne out of the likelihood and into the prior. What do you think @awohns ?

**Comment by hyanwong** [comment]
It would be nice to make this switch before tsdate 1.0, @awohns: what do you think? I know it's not vital, but it's really helpful conceptually, for me at least.

**Comment by awohns** [comment]
Sure, I'll try changing it

**Comment by hyanwong** [comment]
Great, thanks

**Comment by awohns** [comment]
So the change here is minimal: we remove we use `2 * mutation_rate` instead of `theta = 4 * Ne * mutation_rate` and then multiply the prior by `2 * Ne`. The rationale is that the coalescent is affected by `Ne` while the likelihood shouldn't be?

**Comment by hyanwong** [comment]
Yes, exactly. We stick all the Ne stuff in the prior, right at the start. Then I don't think we even need to use it again, do we?
