### ISSUE TITLE
add_sampledata_times should raise an error rather than asserting

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsdate#146]
Since setting the wrong number of sites could happen due to user error, this

https://github.com/tskit-dev/tsdate/blob/cee381c850413eba725819e4b4223bef0c104310/tsdate/util.py#L236

should not be an assert, but should be `if samples.num_sites != len(sites_time): raise ValueError('you done bad')` or whatever.

**Comment by awohns** [comment]
Closed by merging #152
