### ISSUE TITLE
Numba type scheduled for deprecation

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsdate#174]
With using the new streaming `logsumexp` I'm now getting this in the tests:

```
tests/test_functions.py::TestLikelihoodClass::test_logsumexp_underflow
  /Users/yan/anaconda3/lib/python3.9/site-packages/numba/core/ir_utils.py:2119: NumbaPendingDeprecationWarning: 
  Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'X' of function 'LogLikelihoods.logsumexp'.
  
  For more information visit https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types
  
  File "tsdate/date.py", line 411:
      @numba.jit(nopython=True)
      def logsumexp(X):
      ^
  
    warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))
```

Looks like it should be a simple fix @awohns?

**Comment by awohns** [comment]
The fix I added in #175 severely impacts performance. We switched from using [reflected lists](https://numba.pydata.org/numba-doc/latest/reference/deprecation.html) to [typed lists](https://numba.pydata.org/numba-doc/latest/reference/deprecation.html). It looks like [numba developers have encountered many problems with list reflection](https://numba.pydata.org/numba-doc/latest/reference/deprecation.html), which is the reason for the deprecation warning that @hyanwong reported.

Converting to typed lists as I've done is expensive, and we can't simply make the inside and outside matricies of type `numba.reflected.List`, so I think the best thing to do now is just roll back the change I made in #175, pin the current version of numba in the requirements, and make a note to address this in the future.

Any thoughts on this @hyanwong and @benjeffery?

**Comment by hyanwong** [comment]
Oh, that's a pain. I agree, pinning to a numba version for the time being seems reasonable (or simply ignoring the deprecation warning for the moment).

**Comment by hyanwong** [comment]
Actually, I think this is done automatically now, so we *should* just be able to unpin numba, as long as we are sure that we only pass numpy arrays to the logsumexp function. If we don't, I guess an error will be raised anyway.

**Comment by hyanwong** [comment]
In fact, this test now passes with the latest numba (0.56.4): I assume that the warning is no longer raised when using numpy arrays as input. So I think we can simply unpin this now? If we have any deprecation warnings in the tests, we can look into it when they pop up.
