### ISSUE TITLE
Change preprocess_ts() defaults

### ISSUE THREAD

**Issue by awohns** [tskit-dev/tsdate#178]
[`tsinfer` issue 491](https://github.com/tskit-dev/tsinfer/issues/491) identified a downstream issue caused when`preprocess_ts` removes sites.
Right now `preprocess_ts` [outputs a warning](https://github.com/tskit-dev/tsdate/blob/af8bcd58fde1b95ff1d7d9f7bdc3f111b51af37a/tsdate/util.py#L138) if the number of sites changes, which says:

>"Different number of sites after preprocessing. Try using **{'filter_sites:' False} to avoid this"

Do we actually want `filter_sites=False` as a default? Interested to hear your opinion @hyanwong

**Comment by hyanwong** [comment]
There's no reason we should filter out nonvariable sites. In fact, there's no reason to filter out individuals, populations, etc either. So I think we should pass

```
filter_populations=False, filter_individuals=False, filter_sites=False
```

as the default. Shall I make a PR?
