### ISSUE TITLE
Add option for a flat prior 

### ISSUE THREAD

**Issue by awohns** [tskit-dev/tsdate#179]
It would be helpful to implement an option for a flat prior, in cases where the constant time coalescent prior is unsuitable. This can be done easily now using:
```
priors = tsdate.build_prior_grid(ts)
priors.grid_data[:] = np.ones_like(priors.grid_data[:])
dated = tsdate.date(ts, Ne=10000, mutation_rate=1e-8, progress=True, priors=priors)
```
But either create a new function:
```
priors = tsdate.build_flat_prior_grid(ts)
```
or an option to `tsdate.build_prior_grid`:
```
priors = tsdate.build_flat_prior_grid(ts, prior_distr="flat")
```
Would be more convenient (and prevent the unnecessary creation of the conditional coalescent prior in these instances).

**Comment by hyanwong** [comment]
I wonder if we should think about this as a "flat" prior? It's more like we don't inject a coalescent prior, and are only guided by the mutations on branches above and below. It's more obvious when drawn as a factor graph, I think.

**Comment by awohns** [comment]
So how about:
`dated = tsdate.date(ts, Ne=10000, mutation_rate=1e-8, progress=True, priors=None)`
We just have to double check that not using a prior is the same as using a flat prior where everything is 1.

**Comment by hyanwong** [comment]
@minesrebollo would be interested in this. As part of it, I note that Ne should (I think) only be incorporated into the prior now, so it shouldn't be possible to specify both Ne *and* a prior. Is that right @awohns ?

**Comment by awohns** [comment]
Great to hear @minesrebollo is interested!

@hyanwong, the following now results in an error:
```
dated = tsdate.date(ts, Ne=10000, mutation_rate=1e-8, progress=True, priors=priors)
ValueError: Cannot specify Ne in tsdate.date() or tsdate.get_dates() if specifying priors from tsdate.build_prior_grid()
```

But 
`dated = tsdate.date(ts, Ne=10000, mutation_rate=1e-8, progress=True, priors=None)`
is allowed because priors is set to `None`: it just creates a prior with the specified Ne and then dates the tree sequence. 

Do you agree this is a good syntax for running `tsdate` without a prior (changing the behaviour I just described above)?

**Comment by hyanwong** [comment]
Ah, so specifying `Ne` but no prior creates a coalescent prior (with constant Ne) but setting Ne=None *and* prior = None means that we don't use any prior. And you can't set prior=something *and* Ne=something. Is that right?

**Comment by awohns** [comment]
> Ah, so specifying Ne but no prior creates a coalescent prior (with constant Ne) 

Yes

> but setting Ne=None and prior = None means that we don't use any prior.

This is what we'd implement (simple to do)

> And you can't set prior=something and Ne=something. Is that right?

Correct

**Comment by hyanwong** [comment]
Right. That all sounds sensible, as long as it's documented that if you set the prior by hand then you have to set Ne=None. Should we *require* Ne to be specified, do you think (i.e. not give it a default of None)?

Presumably Ne is the "normal" param that people would use, and prior is the "expert" option.

**Comment by awohns** [comment]
> as long as it's documented that if you set the prior by hand then you have to set Ne=None.

After a bit of thought, I think simpler to just say that you can _either_ pass an argument to the `Ne` and `priors` parameters of `tsdate.date()`, not both (even if they agree).
So something like the following:
- `priors = tsdate.build_priors_grid(ts, Ne=None)` --> build a non-coalescent/flat prior
- `tsdate.date(ts, priors=priors)` --> date ts using previously built non-coalescent/flat prior
- `tsdate.date(ts, Ne=None)` --> same as previous, date ts using a non-coalescent/flat prior
- `tsdate.date(ts, priors=None)` --> returns an error, must specify `Ne` if `priors` is `None`
- `tsdate.date(ts, Ne=None, priors=None)` --> returns an error, can't specify both `Ne` and `priors`
- `tsdate.date(ts, Ne=10000, priors=priors)` --> returns an error, can't specify both `Ne` and `priors`
- `tsdate.date(ts, Ne=None, priors=priors)` --> returns an error, can't specify both `Ne` and `priors`, even if they actually agree in this case

What do you think @hyanwong?

> Presumably Ne is the "normal" param that people would use, and prior is the "expert" option.

That's how I think of it

**Comment by hyanwong** [comment]
Hmm, that sounds complicated. Also, I assume by default priors=None, so you can't distinguish between `tsdate.date(ts, Ne=None, priors=None)` and `tsdate.date(ts, Ne=None)`.

Another option is to explicitly specify no prior by setting `priors=False` (and presumably not setting Ne to anything). I think we want to ask @benjeffery or @jeromekelleher what the sensible thing to do here is.

**Comment by hyanwong** [comment]
We are moving to the idea, at least in variational and/or EP-like dating, that we will use an improper uninformative ("flat") prior anyway. I think we can therefore close this issue in favour of one that reworks the entire scheme of providing a prior.

**Comment by nspope** [comment]
For inside-outside, one needs to pick timepoints somehow -- so might not be able to avoid having a population-size based prior there?
