### ISSUE TITLE
mutation_rate as a required parameter

### ISSUE THREAD

**Issue by awohns** [tskit-dev/tsdate#185]
The fact that `mutation_rate` is an optional parameter appears to be causing some confusion for users of tsdate. I propose that we make it a required parameter, and that users must specify `mutation_rate=None` if they want to run `tsdate` without the mutation-based likelihood.

Thoughts: @hyanwong, @benjeffery, @jeromekelleher?

**Comment by jeromekelleher** [comment]
SGTM. Things should only be the default if you think that's usually the best option for most users.

**Comment by hyanwong** [comment]
Seems reasonable to me too.
