### ISSUE TITLE
Add LiTI to Tsdate?

### ISSUE THREAD

**Issue by swamidass** [tskit-dev/tsdate#186]
See here: https://github.com/tskit-dev/tskit/discussions/1635

We have a an implementation of the LiTE algorithm, which infers population demography from a dated ARG. Would it make sense to contribute it to tsdate?

**Comment by awohns** [comment]
Hi @swamidass, your preprint is really fascinating and the method looks great! 
With regards to adding the algorithm to tsdate, after looking at the LiTi algorithm I think it's better suited as a stand-alone piece of software which operates on a tree sequence dated with tsdate. Right now we don't plan to add demographic inference to the model.

**Comment by swamidass** [comment]
Thanks. We'll see what do can do then. Our group doesn't do too much work in this space, at least not yet, so I'd hope we can get this library into the ts family of programs for the longer term.
