### ISSUE TITLE
require that tree sequences are simplified

### ISSUE THREAD

**Issue by awohns** [tskit-dev/tsdate#187]
Currently, we allow tree sequences to be dated if they are unsimplified. `tsdate` does not perform well in this case, and there doesn't seem to be any reason to allow it, so I propose raising a `ValueError` if users attempt to date an unsimplified tree sequence.

**Comment by jeromekelleher** [comment]
How do you detect this?

**Comment by awohns** [comment]
If we [detect unary nodes](https://github.com/tskit-dev/tsdate/blob/7b999ae3a58ac85f182b5c12bcc170e22e4c9f90/tsdate/prior.py#L536), [dangling nodes](https://github.com/tskit-dev/tsdate/blob/7b999ae3a58ac85f182b5c12bcc170e22e4c9f90/tsdate/prior.py#L523), or [nodes that aren't in any tree](https://github.com/tskit-dev/tsdate/blob/7b999ae3a58ac85f182b5c12bcc170e22e4c9f90/tsdate/prior.py#L815) (links to where these are detected in the code).
It's possible that these three criteria don't catch all unsimplfied tree sequences, but these are the features of an unsimplified tree sequence that could cause issues with our prior distribution. A downside of this is that we don't immediately fail if somebody inputs an unsimplified tree sequence.

Alternatively, I was thinking we could look at the metadata to see if `simplify()` had been run, but then we'd need an exception for simulated trees... didn't seem as clean.

**Comment by jeromekelleher** [comment]
Sgtm. You could just warn on detecting the conditions above though?

**Comment by awohns** [comment]
> Sgtm. You could just warn on detecting the conditions above though?

So that's what we do currently, but it looks like some users have still neglected to simplify before dating, with wonky results. One possibility would be to have a parameter such as `allow_unsimplified` which would allow users to proceed (for whatever reason) with an unsimplified tree sequence and get a warning instead of an error, but I don't know if that's even necessary

**Comment by jeromekelleher** [comment]
Ah - well just error out then. If there's a good reason for allowing it then folks can open an issue with a feature request.
