### ISSUE TITLE
Support time units in tree sequence

### ISSUE THREAD

**Issue by awohns** [tskit-dev/tsdate#189]
`tskit` version 0.4.0 includes a [metadata field for the time units used in a tree sequence](https://github.com/tskit-dev/tskit/commit/57eb243582f3ea349800b4f37b06572a857a6da3). We need to support this when it is released: possibly the only thing we need to do for now is set the metadata field to generations in the outputted tree sequence.

**Comment by hyanwong** [comment]
We should probably just leave it as "undefined" for the time being, as we don't know if it's generations or years, or thousands of years, or quite what (it depends on the units of the mutation rate).

Later we could have an optional parameter to specify the units, I guess?

**Comment by hyanwong** [comment]
Fixed in #195
