### ISSUE TITLE
circleci failing, but tests pass locally?

### ISSUE THREAD

**Issue by awohns** [tskit-dev/tsdate#197]
After merging #188, the circle ci fails, though pytest passes on my machine. Any idea what could be causing this @hyanwong or @benjeffery?

**Comment by awohns** [comment]
Very strange. Looks like CircleCi is hanging without output for 10 minutes so it fails:

> Too long with no output (exceeded 10m0s): context deadline exceeded

And I've isolated the problem test [to this one](https://github.com/tskit-dev/tsdate/blob/e1dae30acbfa9dcc366168a4a6ddbdc3666c4d76/tests/test_functions.py#L660), which tests the multithreading when precalculating the likelihood. This code was not changed in the last PR, so I have no idea why it's suddenly not working on CircleCI. Could have something to do with some [issue they're having currently...](https://status.circleci.com/)

**Comment by benjeffery** [comment]
I don't have perms to trigger a re-run, I'd try that first.

**Comment by awohns** [comment]
I've triggered a re-run, still getting the same issue. Do you have any idea why multithreading would suddenly cause an issue?

**Comment by benjeffery** [comment]
> I've triggered a re-run, still getting the same issue. Do you have any idea why multithreading would suddenly cause an issue?

No, and nothing else has changed? Can you try re-running a workflow that previously succeeded, e.g. https://app.circleci.com/pipelines/github/tskit-dev/tsdate/631/workflows/9546f2f2-9a11-4642-97cf-262c0cd926a7/jobs/632

**Comment by awohns** [comment]
Reran that workflow and now it fails with the same timing-out error...

**Comment by benjeffery** [comment]
> Reran that workflow and now it fails with the same timing-out error...

Great, nothing to do with your change then! I'll have a look later today

**Comment by awohns** [comment]
Any thoughts on this @benjeffery?

**Comment by hyanwong** [comment]
Still happening. Ouch.

**Comment by benjeffery** [comment]
Sorry, I still haven't gotten to the bottom of this. Will try to get to it later today.

**Comment by hyanwong** [comment]
That would be great, thanks Ben. I would quite like to make a new tsdate release as we've opened up some useful new functionality (namely getting the posterior out of the function)

**Comment by benjeffery** [comment]
I've fixed this by running the tests in a single thread, the tests are fast so this should be all good.
