### ISSUE TITLE
Add population_size as alias for Ne

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsdate#202]
Since `msprime.sim_ancestry` now uses `population_size` as the parameter name, why don't we also add this as an alias?

**Comment by gregorgorjanc** [comment]
Are you talking here about the number of samples or the effective population size (Ne)? These are two different things.

**Comment by hyanwong** [comment]
$N_e$ - the equivalent to `msprime.simulate(10, Ne=1)` is now `msprime.sim_ancestry(10, population_size=1)`, so we should allow `population_size` as and alias for Ne.

**Comment by hyanwong** [comment]
Fixed in https://github.com/tskit-dev/tsdate/pull/248
