### ISSUE TITLE
Readthedocs "latest" version not updating

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsdate#221]
https://tsdate.readthedocs.io/en/latest/introduction.html says "Please wait to use tsdate in your published work until the release of our preprint." although the GitHub doc has the updated text:

https://github.com/tskit-dev/tsdate/blob/main/docs/introduction.rst

I think this means that `lasted` is not being updated correctly.

**Comment by benjeffery** [comment]
@awohns I've just tried to debug this, but I don't think I have admin rights on readthedocs. Do you?

**Comment by awohns** [comment]
@benjeffery Just sent you an invite to be a maintainer

**Comment by benjeffery** [comment]
> @benjeffery Just sent you an invite to be a maintainer

Thanks, I'm in.

**Comment by benjeffery** [comment]
Apologies, this was an oversight when I changed `master`->`main`. Read the docs was still using `master`. I've updated the configuration and it is deploying the latest docs now.
