### ISSUE TITLE
Allow scaling function for Ne

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsdate#228]
Prompted by discussion with @gregorgorjanc and @nspope, I wonder whether, if we wish to allow a variable Ne, we can simply allow a *function* to be passed to [build_prior_grid](https://tsdate.readthedocs.io/en/latest/python-api.html#tsdate.build_prior_grid) (code [here](https://github.com/tskit-dev/tsdate/blob/77aa23074df155dad6cce8be59d4030bf93536fa/tsdate/prior.py#L999)) as an alternative to a fixed Ne parameter.

The way I would imagine it is that we remove the `Ne` from the `ConditionalCoalescentTimes` class, so that the means and variances stored in `base_priors` are quoted in "canonical" coalescent scaled time, and the mixture prior values will also be in canonical time. We then recode `fill_priors` to to the time-rescaling using either a fixed Ne or a function, and allocate timepoints within that function as appropriate.

**Comment by hyanwong** [comment]
At the same time we might as well fix #202

**Comment by hyanwong** [comment]
As @nspope points out in slack, essentially all we are doing here is rescaling the boundaries of the timeslices (i.e. the timepoints), which we could do by having a scaling function `rescale_to_generations(timepoints_in_coalescent_units, ne_func)` that created a new set out timepoints. However, it might be useful to be able to change the number and distribution of timepoints as well, which would entail recalculating the grid.

Assuming that we want to re-use the conditional coalescent prior (see https://github.com/tskit-dev/tsdate/issues/237#issue-1528674616, suggestion (b)), we probably want to store the alpha and beta parameters for the mixture prior somewhere, so that we can reuse them to allocate Ne-scaled priors into the grid. That means we want to store the result of `get_mixture_prior_params` in some sort of cached object.

**Comment by nspope** [comment]
Could be closed with #252, as the `MixturePrior` class saves the prior params and does rescaling
