### ISSUE TITLE
Shifting copyright for altered files to Tskit Developers

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsdate#234]
As mentioned on Slack, once there are contributors to tsdate that are not working in Oxford, we should probably have a copyright on newly altered files that says something like:

```
# MIT License
#
# Copyright (c) 2021-23 Tskit Developers
# Copyright (c) 2020-21 University of Oxford
```

(I'm not sure if the dates are right here, through). Making this change to recently altered files also makes it trivial for others to contribute later too, as long as they are happy to be described as a tskit developer.

It looks like it is just @awohns, @benjeffery and myself who are contributors at the moment, so this would apply to any files altered by Wilder after he left Oxford. @awohns: when did you officially leave Oxford?

Are we all happy to be described as "Tskit Developers" in the copyright like this? I certainly am.

Also just to check with @jeromekelleher that this is the right thing to do.

**Comment by benjeffery** [comment]
Sounds sensible to me!

**Comment by jeromekelleher** [comment]
LGTM

**Comment by awohns** [comment]
Sounds good to me too!

**Comment by hyanwong** [comment]
Great, thanks all. I will close this issue and change the headers as files get modified in other PRs
