### ISSUE TITLE
Remove `ignore_oldest_root` option from CLI

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsdate#262]
Now that tsinfer splits up the oldest root, this option is unlikely to be needed much. We can leave it in the Python API, but I think we can remove it from the CLI entirely. What do you think @awohns ? This is an API change: I guess we could mark it as deprecated somehow.

**Comment by hyanwong** [comment]
In the CLI we can put:
```
help="Obsolete option. If you wish to ignore the oldest root, use the Python API."
```

and raise an error if it is used.

**Comment by awohns** [comment]
Deprecating it sounds good to me!

**Comment by hyanwong** [comment]
I'm just going to remove this entirely. No point in maintaining an outdated option
