### ISSUE TITLE
Allow a "control" dictionary to be passed to .date()

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsdate#284]
This would be different between the different methods. In particular, if could be used to pass "max_iterations" (or equivalent) to the `variational_dates()` function. See e.g. https://github.com/tskit-dev/tsdate/pull/257#issuecomment-1578295253

**Comment by hyanwong** [comment]
It feels as if we have decided against this approach now, and are simply coding parameters separately for each method. Is that right @nspope?

**Comment by nspope** [comment]
Yes, I think the current approach is cleaner.
