### ISSUE TITLE
Example of incorrect mutation count in `Likelihoods`

### ISSUE THREAD

**Issue by nspope** [tskit-dev/tsdate#308]
Benchmarking on simulated+inferred tree sequences (example: [inferred.zip](https://github.com/tskit-dev/tsdate/files/12373854/inferred.zip)), there are occasionally very large outliers:

<img src="https://github.com/tskit-dev/tsdate/assets/5767783/f4faa0ae-74ba-4c14-b8dd-cde407489fbc" width="40%">

Looking at the EP updates for this node, one of its incoming edges has been allocated a very large number (218) of mutations. For example,
```
import tskit
import tsdate
import numpy as np
ts = tskit.load("inferred.trees")
mut_edges = tsdate.core.VariationalLikelihoods(ts).mut_edges
# array([  1,   1,   0, ...,   0,   1, 218])
```

But this appears to be incorrect, because in the tree sequence only a single mutation is allocated to this edge:
```
outlier_edge = np.where(mut_edges == 218)[0][0] # edge 106980
print([m for m in ts.mutations() if m.edge == outlier_edge])
# [Mutation(id=181693, site=181469, node=22917, derived_state='T', parent=-1, metadata=b'', time=nan, edge=106980)]
```

It seems fishy that the problematic edge here is the last in the array. `VariationalLikelihoods` is inheriting from `Likelihoods` so my guess is the problem lies somewhere in there.

**Comment by nspope** [comment]
I see the problem; here's the relevant code snippet from `Likelihoods`:

```python
    @staticmethod                                                                                               
    def get_mut_edges(ts):
        """                                                                                                     
        Get the number of mutations on each edge in the tree sequence.                                          
        """                                                                                                     
        mut_edges = np.zeros(ts.num_edges, dtype=np.int64)                                                      
        for m in ts.mutations():                                                                                
            mut_edges[m.edge] += 1                                                                              
        return mut_edges  
```

and there are mutations with `m.edge == -1`
```python
len([m for m in ts.mutations() if m.edge == -1])
# 217
```

**Comment by hyanwong** [comment]
Oh, nice catch. That's a nasty bug, but presume lay easy to fixe. I should have put an assertion in there.
