### ISSUE TITLE
add discrepancy function and related things

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tsdate#313]
We would like to add to [`tsdate.evaluation`](https://github.com/tskit-dev/tsdate/blob/main/tsdate/evaluate_accuracy.py):
1. break ties in [`match_node_ages`](https://github.com/tskit-dev/tsdate/blob/main/tsdate/evaluation.py#L228) by closest-in-time (and rename to `match_nodes`, which requires changing the code wherever the function is used)
2. add a `discrepancy` method that returns for the discrepancy between `tsa` and `tsb`, the tuple of
   a. the total shared span divided by total node span in `tsa` (which we need to compute); so this is proprotion of the span in `tsa` that is accurately represented in `tsb`; and
   b. the root-mean-squared discrepancy in time, with the average weighted by span in `tsa`.

**Comment by petrelharp** [comment]
@hfr1z3

**Comment by nspope** [comment]
`match_node_ages` isn't used anywhere else in this repo (only in my own evaluation/paper repo) and it's not documented-- so should be perfectly fine to just change the name in `tsdate.evaluation`

**Comment by hfr1tz3** [comment]
@petrelharp , I wrote up a discrepancy function with the desired outputs.
However, I need to double check if it correctly outputs the correct RMSE that @nspope is looking for. 

I did run the following test case:
For simulated tree sequence ts, let sts = ts.simplify() and ets = sts.extend_edges().
Then tree_discrepancy(ets, ts) has discrepancy value of 1 and rmse of 0.
This makes sense as all of ets should be in ts, and there should therefore be zero error so I think it should be correct, but please double check if I missed something.

**Comment by petrelharp** [comment]
Hm, let's see. I agree with the check that you have. Here's some other possible checks:

1. Perturb the `times` of (some of) the nodes, so you know what the correct RMSE should be. (You could get a set of guaranteed legal perturbations by first iterating over the trees and finding an upper bound for each node by the lowest time of an ancestor across the trees; then only perturb nodes up.)
2. Make a very simple example where we know the right answer.

**Comment by hyanwong** [comment]
Closing this as it's being moved to https://github.com/tskit-dev/tscompare
