### ISSUE TITLE
Speed up pre-algorithm steps

### ISSUE THREAD

**Issue by nspope** [tskit-dev/tsdate#355]
I'm running tsdate on a large tree sequence (74mil edges) and noticing that the pre-algorithm steps are quite costly. In particular, there's a call to `ts.simplify()` in `util.reduce_to_contemporaneous()` that really slows things down. It'd be good to profile and try to slim these steps down as much as possible.

**Comment by nspope** [comment]
Another bottleneck is finding node spans for the prior.

**Comment by hyanwong** [comment]
> Another bottleneck is finding node spans for the prior.

An efficient number's implementation to get the spans-by-samples data would be good to include in https://github.com/tskit-dev/tutorials/issues/233 I think.

**Comment by hyanwong** [comment]
We don't use this any more in variational_gamma, right @nspope ? So should we simply close this?
