### ISSUE TITLE
Use timeslices, not timepoints, with children & parents allowed in the same timeslice

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsdate#36]
We should eventually switch to a world where the discrete time points are considered as slices in time, e.g. time 0-1, 1-3, 3-5 etc. rather than discrete points. For this, the main issue is that we should allow children and their parent nodes to exist within the same timeslice.

I don't think this is allowed at the moment. It shouldn’t, however, be a problem for the priors, the likelihood calculation, and the dynamic programming, but it will be problematic when we convert back into a tree sequence, which quite reasonably enforces children to be younger than parents.

The obvious thing to do is to adjust this when we interpret the tables as a tree sequence, e.g. we could space out the parent/offspring nodes *within* a timeslice according to some exponential or gamma model (I haven’t quite worked out the algorithm yet). One good way to test this would be to get tsdate working with a tiny number of timeslices (e.g. only 2), and see how we would fix the resulting problems.

**Comment by awohns** [comment]
This is the epsilon issue discussed at meeting on 28th of October, 2019. 
Epsilon should be a function of where slices are placed. Think of the proper epsilon as the probability of a mutation within the same time slice

**Comment by hyanwong** [comment]
Could you upload into this thread the picture of the whiteboard in Gil's office thats relevant to this issue, @awohns ?

**Comment by awohns** [comment]
I’m not sure there was anything about this written on the whiteboard... it might be in my notes which I can check tomorrow morning.

**Comment by hyanwong** [comment]
No longer relevant, I think
