### ISSUE TITLE
Cache JIT compiled code

### ISSUE THREAD

**Issue by nspope** [tskit-dev/tsdate#368]
Currently, importing tsdate has a lot of overhead from JIT compilation. It'd be great to cache compiled code, so the import overhead only occurs once, but this fails when the JIT'd functions use `scipy`'s cython implementations of special functions. The use of `scipy.special` is minimal at this point, and shouldn't be hard to drop entirely.

**Comment by jeromekelleher** [comment]
Be wary of this - we've had major problems with numba caching in sgkit, and are about to disable it by default

**Comment by nspope** [comment]
Darn, good to know. An alternative would be to build these into a module, I guess?

**Comment by jeromekelleher** [comment]
I'd just leave it to be honest. Hopefully numba will sort it soon, and then we can revisit

**Comment by hyanwong** [comment]
It's causing the docs build to fail. Can we increase the time available for jupyterbook building in any way?

**Comment by nspope** [comment]
Looks like it: https://jupyterbook.org/en/stable/content/execute.html#setting-execution-timeout
