### ISSUE TITLE
Branch/site statistic mismatch and inferred tree sequences

### ISSUE THREAD

**Issue by nspope** [tskit-dev/tsdate#370]
We've been looking at site vs branch diversity to assess at a glance whether an inferred + dated tree sequence has a reasonable timescale. However, this may not be the best metric to use: diversity will be very sensitive to the ages of the roots; and if there are polytomies then branch diversity will be biased downward even if the node times themselves are more-or-less correct.

Instead, number of segregating sites -- which reflects total mutational area, and should have less bias from topological oddities -- might be a better metric. For example (using https://github.com/nspope/tsdate/tree/fix-timescale branch):

```python
mutation_rate = 1.25e-8

ts = msprime.sim_ancestry(
    samples=10000,
    sequence_length=1e6,
    recombination_rate=1e-8,                                                                                                                                                          
    population_size=1e4,
    random_seed=101,
)
ts = msprime.sim_mutations(
    ts,
    mutation_rate,
    random_seed=101,
)
```

After dating the true (binary) trees, site/branch diversity match, as do segregating sites
```python
dated_ts = tsdate.date(ts, mutation_rate=mutation_rate, method="variational_gamma")
print(dated_ts.segregating_sites(), dated_ts.segregating_sites(mode='branch')*mutation_rate)
# 0.00504 0.0050420000000000135 <<<<---- segregating sites is very close
print(dated_ts.diversity(), dated_ts.diversity(mode='branch')*mutation_rate)
# 0.0005021164979348875 0.0004909551221402414 <<<<----- diversity is very close
```

In contrast, if we date (not binary) inferred trees, there's a mismatch between site/branch diversity but *not* between site/branch segregating sites:
```python
import tsinfer
inf_ts = tsinfer.infer(tsinfer.SampleData.from_tree_sequence(ts)).simplify()
dated_inf_ts = tsdate.date(inf_ts, mutation_rate=mutation_rate, method="variational_gamma")
print(dated_inf_ts.segregating_sites(), dated_inf_ts.segregating_sites(mode='branch')*mutation_rate)
# 0.00504 0.005053000000000065 <<<<---- segregating sites is very close
print(dated_inf_ts.diversity(), dated_inf_ts.diversity(mode='branch')*mutation_rate)   
# 0.0005021164979348875 0.0003818506534425654 <<<<---- but diversity is underestimated
```

Any thoughts on this, @hyanwong and @petrelharp?

**Comment by petrelharp** [comment]
Great idea - segregating sites counts each bit of the tree once, so seems like a better metric anyhow.

**Comment by hyanwong** [comment]
This seems good (and right) to me. Here are the results of the `fix-timescale` branch dating on the Genomics England data:

Without singletons:
![screenshot_2024-02-16_at_00 00 10_720](https://github.com/tskit-dev/tsdate/assets/4699014/5274b516-be68-48ab-ade8-7333850c401e)

![screenshot_2024-02-16_at_07 44 53_720](https://github.com/tskit-dev/tsdate/assets/4699014/a88b4906-0cd4-41ba-abab-abb6dea95dfc)


With singletons

![screenshot_2024-02-16_at_08 48 22_720](https://github.com/tskit-dev/tsdate/assets/4699014/a926d4ad-988e-40d9-8d80-2a329286a7ea)

**Comment by jeromekelleher** [comment]
> Should we be worried about the discrepancy between 0.01339734 and 0.01351895 here, given that the method is trying to make these the same?

This seems like really  close match to me!

**Comment by hyanwong** [comment]
> > Should we be worried about the discrepancy between 0.01339734 and 0.01351895 here, given that the method is trying to make these the same?
> 
> This seems like really close match to me!

99%: it's not as close as in the test data. I would hope that with more iterations we would tend to the exact value?

**Comment by jeromekelleher** [comment]
Sounds about as good as that sort of thing gets with real data to me - if it was any closer I would doubt its value

**Comment by nspope** [comment]
Looking at the allele frequency spectrum, which is effectively just chopping up segregating sites into bins, would give a more fine-scaled view of the fit.
