### ISSUE TITLE
Set sensible rescaling-intervals default value and save in provenance

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsdate#378]
In some of the tests we set rescaling-intervals to 0, presumably for speed reasons. It would be sensible to have a value which was a function of the number of (internal?) nodes in the tree sequence, at least for smaller tree sequences, e.g. `rescaling_intervals=None` could default to min(num_nonsample_nodes / 5, 1000)`.

We should save the calculated `rescaling_intervals` value in the provenance of the resulting dated tree sequence, so we can retrieve it afterwards if necessary.

**Comment by hyanwong** [comment]
We now save it in provenance. Default of 1000 seems OK. We could revisit later

**Comment by nspope** [comment]
Sounds good. I have a way to automatically determine the number of intervals that should ultimately be used, but haven't fully tested it yet.
