### ISSUE TITLE
Dating dangling nodes 

### ISSUE THREAD

**Issue by awohns** [tskit-dev/tsdate#38]
We currently can't date an unsimplified tree sequence with dangling nodes. We might want to think about how to do this, the problem is that there isn't a clear prior for these nodes.

**Comment by hyanwong** [comment]
To be clear, we might want to leave dangling edges in place because they are useful attachment points for augmented samples. Unfortunately they may be hard (impossible?) to date because of the lack of prior

**Comment by hyanwong** [comment]
It should be possible to assign the global prior to these nodes now

**Comment by hyanwong** [comment]
Not longer an issue for `variational_gamma`.
