### ISSUE TITLE
variational_gamma does not seem to return posteriors

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsdate#388]
```python
import msprime
ts = msprime.simulate(10, mutation_rate=1, random_seed=1)
tsdate.variational_gamma(ts, mutation_rate=1, return_posteriors=True)

# Gives `(<tskit.trees.TreeSequence at 0x10ed3a980>, None)`
```

I think we intended to return the shape and rate params as a pandas data frame, right @nspope ?

**Comment by nspope** [comment]
Given they're stored in the metadata, it'd be nicer to have a convenience function that extracts them and dumps them into a pandas dataframe.

**Comment by hyanwong** [comment]
I'm assuming that it's pretty trivial to actually return the shape and rate. We have all that calculated anyway, right?

**Comment by nspope** [comment]
Yup, it's easy enough to do. Let's return a numpy array for vgamma rather than a pandas dataframe, though.

**Comment by nspope** [comment]
> we should return a dict

I think we should return a numpy array, if we're going to return variational posteriors -- there's a natural indexing for nodes, there's always two values per node, and it's effectively free (populating a dict isn't free). I wouldn't worry about matching whatever is done for inside-outside -- vgamma has effectively diverged enough that I think we can consider these to be two separate APIs (one under development, one retained for legacy reasons).

**Comment by hyanwong** [comment]
I agree it isn't pressing.

The reason for returning a dict, or equivalent, is also that we can assign node IDs to each set of parameters. I guess we could simply return an array of width ts.num_nodes, with NaNs for nodes that don't have posteriors, though.

**Comment by nspope** [comment]
Yup, that's exactly what I'm thinking. I'd store it as num_nodes by 2 so that node access is posteriors[node].

**Comment by hyanwong** [comment]
It would also be OK, IMO, to return a dict of `{'shape': np.array, 'rate': np.array}`, which would also be of trivial cost, but would have the advantage of documenting the meaning of the columns.

**Comment by hyanwong** [comment]
Actually, if there are many missing values (undated nodes) it could be worth implementing as

`{'node_id': np.ints, 'shape': np.array, 'rate': np.array}`

**Comment by nspope** [comment]
The number of undated nodes is never going to be huge. Because there's a natural indexing, let's keep it at full-length arrays.

**Comment by hyanwong** [comment]
I'm wondering whether we should use a new name "return_node_posteriors" (rather than simply "return_posteriors", as

1. We could also return mutation posteriors, so this is clearer
2. We could deprecate the return_posteriors option, then get the inside_outside method to return the posteriors in the same form (nodes-by-timepoints compared to nodes-by-parameters). At the moment it returns timepoints-by-nodes, and it would be nice to have something consistent.

**Comment by hyanwong** [comment]
Closing in favour of #410
