### ISSUE TITLE
variational_gamma method fails on tree seq with no mutations

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsdate#390]
```python
import msprime
ts = msprime.simulate(10, mutation_rate=0, random_seed=1)
tsdate.variational_gamma(ts, mutation_rate=1, return_posteriors=True)
# fails with --> 233 assert np.all(np.diff(rescaled_breaks) > 0)
```

I don't think this is a problem, but maybe we should detect it and error out early with a warning to use a different method?

**Comment by hyanwong** [comment]
Ah, it just needs `rescaling_intervals=0`

**Comment by hyanwong** [comment]
So we should probably say that `rescaling_intervals=None` sets the default to 1000 if there are mutations in the tree seq, else 0? Does that sound right @nspope ?

**Comment by hyanwong** [comment]
(Or we could set it to `min(num_mutations, 1000)`

**Comment by nspope** [comment]
I think we should error out if there's no mutations, because the algorithm won't worth correctly in that case.
