### ISSUE TITLE
Remove need for tsinfer (and matplotlib?) from requirements.txt

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsdate#393]
These should only be needed for building docs and testing.

We should probably move to the tskit system of having separate requirements files for different purposes. I wonder if @benjeffery could advise?

**Comment by benjeffery** [comment]
Could do - I assume not many people apart from developers are installing from source, so it is not a big deal if there are extra packages in requirements.txt, the PyPI install will be using those specified in setup.cfg.

**Comment by hyanwong** [comment]
Ah, right. I forgot that it's the setup.cfg.that's used in PyPI. So no urgency: this is a "nice to have".

**Comment by hyanwong** [comment]
Closing, no urgency
