### ISSUE TITLE
Numpy 2 pinning

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tsdate#403]
I've looked into this, and tsdate is implicitly pinned to `numpy<1.27` via the dependency on `numba`. I don't see any other reason why tsdate should be incompatible with numpy 2, so I suggest we don't pin and and check compatibility when a numba release candidate is out. Switching to the numpy ruff linting in the meantime would seem wise.

**Comment by hyanwong** [comment]
Ah, that's good then. Can you push the button to make a release (0.2) anyway?

How do we switch to ruff linting?

**Comment by benjeffery** [comment]
I've just done it over at tskit: https://github.com/tskit-dev/tskit/pull/2952

**Comment by hyanwong** [comment]
Thanks. Shall I make that switch (mostly in `.pre-commit-config.yaml` I guess) for tsdate then?

**Comment by benjeffery** [comment]
I'm happy to pick that up - they'll likely be lots of errors to fix, I have some automated tools for some of them from the tskit switch.

**Comment by hyanwong** [comment]
OH, that's kind, thanks.

**Comment by nspope** [comment]
If there's going to a lot of changes to files across the board, mind waiting until I'm done with the singleton phasing (almost there)? Else there'll be a boatload of merge conflicts

**Comment by hyanwong** [comment]
Maybe we can simply release v2.0 now without the ruff linting, then switch ruff on after the singleton stuff drops, to make v0.2.1?

**Comment by jeromekelleher** [comment]
I don't think there's any hurry with ruff, the numba dependency will be safe for numpy 2 for quite a while. No harm in scheduling the change for immediately after current release though

**Comment by benjeffery** [comment]
Yeah, happy to leave ruff till after the release. @nspope get your PR merged before ruff for sure!

**Comment by benjeffery** [comment]
Closing this as we've decided to release using numba as the implicit pin and to do ruff after release.

**Comment by hyanwong** [comment]
Great. Let me know if I need to do anything to help push a new release version.

**Comment by nspope** [comment]
Thanks @benjeffery !
