### ISSUE TITLE
Mutation metadata mean and variance for unphased singleton mutations

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsdate#414]
An unphased singleton mutation could be on either the maternal or the paternal edge. Does the mean and variance saved in the mutation metadata reflect this possibility (i.e. is X % of the weight taken from the gamma on one edge and (100-X) % from the gamma on the other edge? Or is the mean in the mutation metadata conditioned on having correctly phased the singleton?

**Comment by nspope** [comment]
The mean in the metadata integrates over possible phase, so is the weighted version you describe.
