### ISSUE TITLE
Minor improvement - use new num_children() method

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsdate#62]
Once there is a new tskit release, we should switch to the more obvious (and slightly faster) `tree.num_children(u) == 1` rather than`len(tree.children(u)) == 1`.

**Comment by awohns** [comment]
Can we close this @hyanwong ? We now have the local function instead of a monkey patch

**Comment by hyanwong** [comment]
Leave this issue open until the newest tskit version is released with that functionality baked-in. Then we can change the requirements and use the provided version instead.
