### ISSUE TITLE
Remove the topology-only clock

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsdate#73]
At the moment in the forwards_algorithm, the section labelled `# Topology-only clock` assigns into the vv variable, but then nothing is done with that variable. It looks like there's a mistake there to me.

**Comment by awohns** [comment]
This is pretty old code I added to check the accuracy of the likelihood calculations vs a naive topology-only metric that basically just counts the number of edges beneath a node. 
I can’t think of a time where we’d actually want to use this anymore.

**Comment by hyanwong** [comment]
I guess you meant to do the same as the previous lines, and assign `val *= vv` and probably `g_val *= vv` too in that branch of the if statement?

**Comment by awohns** [comment]
Yes, another bit of code that used to be in there but got lost because we never used/tested the topology-only clock!

**Comment by hyanwong** [comment]
Tests have show that basing node times on a naive expectation under the coalescent based on each marginal tree (what we call the "topology-only" clock) does not give good results (see e.g. https://github.com/tskit-dev/tsdate/issues/292), so I think we should simply remove the ability to do this, and raise a NotImplementedErrro
