### ISSUE TITLE
Does restrict_ages_topo do anything?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsdate#82]
The function `restrict_ages_topo()` seems a hack. I thought we had come to the conclusion that due to the method of production, we never do produce inconsistently dated mean posterior times (although I still find that surprising).

If we choose to produce a final dated TS where we have restricted ages like this, we should say so (and maybe we should use `logging.warning()` to inform the user that some nodes are not dated according to their mean posterior.

This is one reason why I like the idea of using Viterbi, which is guaranteed to be consistent, without the `restrict_ages_topo` hack.

**Comment by awohns** [comment]
@hyanwong do you want to close this?

**Comment by hyanwong** [comment]
If `constrain_ages_topo` results in changed times in the tree sequence, do you think it would be useful to output a logging warning? For method="outside_max" that might give too many warnings, I guess, so we could only warn there if a node changes timeslice?

**Comment by awohns** [comment]
Yes that could be a good idea! You could just say the number of nodes that were changed in the constrain_ages_topo

How would “outside_max” change times? Not quite following you there...

**Comment by hyanwong** [comment]
> On 19 Feb 2020, at 18:01, Anthony Wilder Wohns <notifications@github.com> wrote:
> 
> Yes that could be a good idea! You could just say the number of nodes that were changed in the constrain_ages_topo

Right. Only emit the warning when that number is >0, though.

> How would “outside_max” change times? Not quite following you there…

Oh, good point. I forgot that it’s consistent by design. Silly me.
