### ISSUE TITLE
Simplify root iterations & ts checking using new `root_threshold `

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsdate#96]
As of https://github.com/tskit-dev/tskit/pull/462 there's a new option for trees (or tree sequences) so that we don't report isolated nodes as roots. We should use this to avoid the "is_isolated" check in tsdate.

**Comment by awohns** [comment]
Are we happy to close this @hyanwong? I don't see an "is_isolated" check, must be old?

**Comment by hyanwong** [comment]
Looks like it is[here](https://github.com/awohns/tsdate/blob/c3e155046a6562cff3ed8987d35908d9c31df61d/tsdate/util.py#L48)

**Comment by hyanwong** [comment]
Fixed in #281
